#!/usr/bin/env node
/* Inlines abilitytree/*.js into shooter.html so the game stays a single
   self-contained file that runs from the filesystem with nothing beside it.

   abilitytree/ remains the source of truth - edit there, then run:
       node tools/inline-tree.js
*/
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TARGET = path.join(ROOT, 'shooter.html');
const FILES = ['tree.data.js', 'tree.logic.js', 'tree.ui.js'];
const BEGIN = '<!-- ability-tree:begin (generated by tools/inline-tree.js - do not edit here) -->';
const END = '<!-- ability-tree:end -->';

const blocks = FILES.map(f => {
  const src = fs.readFileSync(path.join(ROOT, 'abilitytree', f), 'utf8');
  // a literal </script> inside the source would close the tag early
  return '<script>/* abilitytree/' + f + ' */\n' + src.replace(/<\/script>/gi, '<\\/script>') + '</script>';
}).join('\n');

let html = fs.readFileSync(TARGET, 'utf8');
const i = html.indexOf(BEGIN), j = html.indexOf(END);
if (i === -1 || j === -1) {
  console.error('markers not found in shooter.html - add:\n' + BEGIN + '\n' + END);
  process.exit(1);
}
html = html.slice(0, i) + BEGIN + '\n' + blocks + '\n' + html.slice(j);
fs.writeFileSync(TARGET, html);
console.log('inlined ' + FILES.length + ' module files into shooter.html (' + Math.round(blocks.length / 1024) + ' KB)');
